apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: todo-app-backend
  namespace: sample-project
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: todo-app
        tier: todo-app-backend
        track: stable
    spec:
      containers:
        - name: todo-app-backend
          image: "jeffleevm/todo-app-backend:latest"
          ports:
          - containerPort: 8080
