apiVersion: v1
kind: Service
metadata:
  name: todo-app-backend
  namespace: sample-project
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: todo-app
    tier: todo-app-backend
  type: ClusterIP
