apiVersion: v1
kind: Service
metadata:
  name: demo-todo-app-backend
  namespace: demo-project
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: demo-todo-app
    tier: demo-todo-app-backend
  type: ClusterIP
