apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: mongo
  name: mongo
  namespace: todo-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongo
  name: mongo
  namespace: todo-app
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: mongo
